### ISSUE TITLE
check failed with warnings from multiple thresholds with foreach and doMC

### ISSUE THREAD

**Issue by huangyh09** [single-cell-genetics/cardelino#2]
Build [#73](https://travis-ci.org/PMBio/cardelino/builds/480555137) fails due to warnings, where it says

`
Undefined global functions or variables:
  %dopar%
`

The `%dopar%` is used in multiple thresholds with foreach and doMC in function `vireo_flock` in donor_id.R. Any idea on how to avoid the warning?

Yuanhua

**Comment by jeffreypullin** [comment]
These errors may relate to the (now removed) vireo component and were not observed in recent GitHub Action runs so I'm going to close this issue now.
