### ISSUE TITLE
Is cardelino applicable to 10X or DropSeq data?

### ISSUE THREAD

**Issue by Pentayouth** [single-cell-genetics/cardelino#5]
I'm very interested in cardelino. 
I wonder if cardelino is applicable to 10X/dropseq data which suffers more from data sparsity and dropout events.
Since 10X technique is inferior to SmartSeq2 in sequencing depth, could it's higher throughput be a possible compensate?

Thank you.

**Comment by huangyh09** [comment]
Thanks. in principle, yes. Usually, the number of somatic mutations is not high, so computational efficiency is not an issue yet. If your data set is huge, you may consider [Vireo](https://github.com/single-cell-genetics/vireo), a variational approximation for balancing the efficiency and accuracy.

Yuanhua

**Comment by Pentayouth** [comment]
Thank you very much for your timely help!
